export const A = [{name:"ANU", Page:"https://customdemo.website/apps/JP-Guide/upload/ANU.pdf"}, {name:"AUA", Page : "https://customdemo.website/apps/JP-Guide/upload/AUA.pdf"}]
export const B = [{name:"BAQ", Page:"https://customdemo.website/apps/JP-Guide/upload/BAQ.pdf"}, {name:"BDA", Page:"https://customdemo.website/apps/JP-Guide/upload/BDA.pdf"}, {name:"BGI", Page:"https://customdemo.website/apps/JP-Guide/upload/BGI.pdf"}, {name:"BOG", Page:"https://customdemo.website/apps/JP-Guide/upload/BOG.pdf"}, {name:"BZE", Page:"https://customdemo.website/apps/JP-Guide/upload/BZE.pdf"}]
export const C = [{name:"CAP", Page:"https://customdemo.website/apps/JP-Guide/upload/CAP.pdf"}, {name:"CCS", Page:"https://customdemo.website/apps/JP-Guide/upload/CCS.pdf"}, {name:"CLO", Page:"https://customdemo.website/apps/JP-Guide/upload/CLO.pdf"}, {name:"CUN", Page:"https://customdemo.website/apps/JP-Guide/upload/CUN.pdf"}, {name:"CUR", Page:"https://customdemo.website/apps/JP-Guide/upload/CUR.pdf"}, {name:"CZM", Page:"https://customdemo.website/apps/JP-Guide/upload/CZM.pdf"}]
// export const D = ["ANU", "AUA"]
// export const E = ["ANU", "AUA"]
export const F = [{name:"FDF", Page:"https://customdemo.website/apps/JP-Guide/upload/FDF.pdf"}]
export const G = [{name:"GCM", Page:"https://customdemo.website/apps/JP-Guide/upload/GCM.pdf"}, {name:"GDL", Page:"https://customdemo.website/apps/JP-Guide/upload/GDL.pdf"}, {name:"GEO", Page:"https://customdemo.website/apps/JP-Guide/upload/GEO.pdf"}, {name:"GND", Page:"https://customdemo.website/apps/JP-Guide/upload/GND.pdf"}, {name:"GUA", Page:"https://customdemo.website/apps/JP-Guide/upload/GUA.pdf"}, {name : "GYE", Page : "https://customdemo.website/apps/JP-Guide/upload/GYE.pdf"}]
export const H = [{name:"HAV", Page:"https://customdemo.website/apps/JP-Guide/upload/HAV.pdf"},{name:"HOG", Page:"https://customdemo.website/apps/JP-Guide/upload/HOG.pdf"}]
// export const I = ["ANU", "AUA"]
// export const J = ["ANU", "AUA"]
export const K = [{name:"KIN", Page:"https://customdemo.website/apps/JP-Guide/upload/KIN.pdf"}]
export const L = [{name:"LIR", Page:"https://customdemo.website/apps/JP-Guide/upload/LIR.pdf"}]
export const M = [{name:"MAR", Page:"https://customdemo.website/apps/JP-Guide/upload/MAR.pdf"}, {name:"MBJ", Page:"https://customdemo.website/apps/JP-Guide/upload/MBJ.pdf"}, {name:"MDE", Page:"https://customdemo.website/apps/JP-Guide/upload/MDE.pdf"}, {name:"MEX", Page:"https://customdemo.website/apps/JP-Guide/upload/MEX.pdf"}, {name:"MGA", Page:"https://customdemo.website/apps/JP-Guide/upload/MGA.pdf"}]
export const N = [{name:"NAS", Page:"https://customdemo.website/apps/JP-Guide/upload/NAS.pdf"}]
// export const O = ["ANU", "AUA"]
export const P = [{name:"PAP", Page:"https://customdemo.website/apps/JP-Guide/upload/PAP.pdf"}, {name:"PLS", Page:"https://customdemo.website/apps/JP-Guide/upload/PLS.pdf"}, {name:"POP", Page:"https://customdemo.website/apps/JP-Guide/upload/POP.pdf"}, {name:"POS", Page:"https://customdemo.website/apps/JP-Guide/upload/POS.pdf"}, {name:"PTY", Page:"https://customdemo.website/apps/JP-Guide/upload/PTY.pdf"}, {name : "PUJ", Page : "https://customdemo.website/apps/JP-Guide/upload/PUJ.pdf"}, {name : "PVR", Page : "https://customdemo.website/apps/JP-Guide/upload/PVR.pdf"}]
// export const Q = ["ANU", "AUA"]
export const R = [{name:"RTB", Page:"https://customdemo.website/apps/JP-Guide/upload/RTB.pdf"}]
export const S = [{name:"SAL", Page:"https://customdemo.website/apps/JP-Guide/upload/SAL.pdf"},{name:"SAP", Page:"https://customdemo.website/apps/JP-Guide/upload/SAP.pdf"} ,{name:"SDQ", Page:"https://customdemo.website/apps/JP-Guide/upload/SDQ.pdf"},{name:"SJO", Page:"https://customdemo.website/apps/JP-Guide/upload/SJO.pdf"},{name:"SJU", Page:"https://customdemo.website/apps/JP-Guide/upload/SJU.pdf"},{name:"SKB", Page:"https://customdemo.website/apps/JP-Guide/upload/SKB.pdf"},{name:"SNU", Page:"https://customdemo.website/apps/JP-Guide/upload/SNU.pdf"},{name:"STI", Page:"https://customdemo.website/apps/JP-Guide/upload/STI.pdf"},{name:"STT", Page:"https://customdemo.website/apps/JP-Guide/upload/STT.pdf"},{name:"STX", Page:"https://customdemo.website/apps/JP-Guide/upload/STX.pdf"},{name:"SXM", Page:"https://customdemo.website/apps/JP-Guide/upload/SXM.pdf"}]
// export const T = ["ANU", "AUA"]
export const U = [{name:"UIO", Page:"https://customdemo.website/apps/JP-Guide/upload/UIO.pdf"},{name:"UVF", Page:"https://customdemo.website/apps/JP-Guide/upload/UVF.pdf"}]
export const V = [{name:"VRA", Page:"https://customdemo.website/apps/JP-Guide/upload/VRA.pdf"}]
// export const W = ["ANU", "AUA"]
export const X = [{name:"XPL", Page:"https://customdemo.website/apps/JP-Guide/upload/XPL.pdf"}]
export const Y = [{name:"YUL", Page:"https://customdemo.website/apps/JP-Guide/upload/YUL.pdf"},{name:"YYZ", Page:"https://customdemo.website/apps/JP-Guide/upload/YYZ.pdf"}]
// export const Z = ["ANU", "AUA"]


